#!/bin/zsh

setopt always_to_end

setopt appendhistory

setopt auto_cd

setopt auto_menu

setopt auto_list

unsetopt auto_remove_slash

setopt bash_auto_list

setopt complete_in_word

setopt extendedglob

unsetopt menucomplete

setopt prompt_subst

