#!/bin/bash

# Set irssi password
pushd .irssi > /dev/null

if [ ! -f 'passwd' ]; then
  echo 'No passwd file found.' >&2
else
  sed -e "s/%pass%/$(cat passwd)/" config.skel > config
fi

popd > /dev/null

# Set RDP settings

pushd .zsh.d > /dev/null

if [ ! -f 'data.sed' ]; then
  echo 'No data file found.' >&2
else
  sed -f data.sed _30_aliases.skel > 30_aliases
fi

popd > /dev/null

